// Generates the Sunmade icon SVGs from the shared geometry in src/brand.js.
// Usage: node make-icons.js
const fs = require('fs');
const vm = require('vm');
const ctx = { Math, console };
vm.createContext(ctx);
vm.runInContext(fs.readFileSync(__dirname + '/src/brand.js', 'utf8') + '\nthis.C = C; this.houseRoofGeometry = houseRoofGeometry;', ctx);
const { C, houseRoofGeometry } = ctx;
const g = houseRoofGeometry();
const [vx, vy, vw, vh] = g.viewBox.split(' ').map(Number);

// Mark scaled into a square canvas of `size`, occupying `fill` of its height, centred.
function placed(size, fill) {
  const scale = (size * fill) / vh;
  const tx = size / 2 - (vx + vw / 2) * scale, ty = size / 2 - (vy + vh / 2) * scale;
  return `transform="translate(${tx.toFixed(2)} ${ty.toFixed(2)}) scale(${scale.toFixed(4)})"`;
}
const markPaths = (house, roof) => `<path d="${g.roofD}" fill="${roof}"/><path d="${g.houseD}" fill="${house}"/>`;

const files = {
  // Primary icon: teal tile, white house, gold roof (the approved app icon)
  'sunmade-icon.svg': `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" width="512" height="512"><title>Sunmade</title>
  <rect width="512" height="512" rx="115.2" fill="${C.teal}"/><g ${placed(512, 0.56)}>${markPaths(C.white, C.gold)}</g></svg>`,
  // Full-bleed square for iOS / Android masks (the platform rounds the corners)
  'sunmade-icon-square.svg': `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" width="512" height="512"><title>Sunmade</title>
  <rect width="512" height="512" fill="${C.teal}"/><g ${placed(512, 0.5)}>${markPaths(C.white, C.gold)}</g></svg>`,
  // Mark without the tile
  'sunmade-mark.svg': `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${g.viewBox}" width="${vw * 3}" height="${vh * 3}"><title>Sunmade</title>${markPaths(C.teal, C.gold)}</svg>`,
  'sunmade-mark-white.svg': `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${g.viewBox}" width="${vw * 3}" height="${vh * 3}"><title>Sunmade</title>${markPaths(C.white, C.gold)}</svg>`,
};
for (const [name, svg] of Object.entries(files)) fs.writeFileSync(`${__dirname}/logo/${name}`, svg + '\n');

// Geometry for the React logo component (src/shared/components/brand/geometry.ts)
const tileTransform = placed(512, 0.56).replace(/^transform="|"$/g, '');
const ts = `// Generated by design/brand/make-icons.js from design/brand/src/brand.js — do not edit by hand.
export const MARK_VIEWBOX = '${g.viewBox}';
export const MARK_HOUSE_PATH = '${g.houseD}';
export const MARK_ROOF_PATH = '${g.roofD}';
/** Places the mark inside a 512 x 512 tile at 56% of its height. */
export const TILE_MARK_TRANSFORM = '${tileTransform}';
export const TILE_RADIUS = 115.2;
`;
fs.writeFileSync(`${__dirname}/../../src/shared/components/brand/geometry.ts`, ts);
console.log('wrote', Object.keys(files).join(', '), '+ src/shared/components/brand/geometry.ts');
